jobs:
- job: create_release_branch
  pool:
    vmImage: 'macOS 10.14'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  - template: templates/set-triager.yml
  - script: npm install
    displayName: Install the Node dependencies
  - script: node ./ci-jobs/scripts/set-rc-tag.js
    displayName: Update package.json version to rc
  - script: |
      export MINOR_VERSION=$(node ./ci-jobs/scripts/output-minor-version.js)
      echo "Creating branch ${MINOR_VERSION}"
      git checkout -b ${MINOR_VERSION}
      git add .
      git commit -n -m 'Release branch ${MINOR_VERSION}'
      git push --force --set-upstream triager HEAD:${MINOR_VERSION}
    displayName: Create the MINOR_VERSION branch
  - template: templates/tag-and-publish.yml
    parameters:
      TAG: ${MINOR_VERSION}.0-fake.0

  # Switch back to master branch, bump the minor version and create a beta
  #- script: |
      #git checkout master
      #git reset --hard triager/master
      #node ./ci-jobs/scripts/bump-minor-version.js
      #rm -rf npm-shrinkwrap.json
      #npm shrinkwrap
      #git push triager master
    #displayName: Bump minor version and set beta to zero