jobs:
- job: create_release_branch
  pool:
    vmImage: 'macOS 10.14'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  - template: templates/set-triager.yml
  - script: npm install
    displayName: Install the Node dependencies
  - script: node ./ci-jobs/scripts/set-rc-tag.js
    displayName: Update package.json version to rc
  - script: |
      export MINOR_VERSION=releases/$(node ./ci-jobs/scripts/output-minor-version.js)
      echo "Creating branch ${BRANCH}"
      git checkout -b ${BRANCH}
      git add .
      git commit -n -m 'Release branch ${BRANCH}'
      git push --force --set-upstream triager HEAD:${BRANCH}
    displayName: Create the MINOR_VERSION branch
  - script: |
      git tag v${MINOR_VERSION}.0-rc.0
      git push --tags triager
    displayName: Git Tag the release candidate