jobs:
- job: master
  pool:
    vmImage: 'macOS 10.14'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  - script: |
      git config --global user.name "triager"
      git remote add triager https://${GH_TOKEN}@github.com/appium/appium.git > /dev/null 2>&1
      git remote show triager
    displayName: Set TRIAGER as Git user
  - script: npm install
    displayName: Install the Node dependencies
  - script: |
      git tag v${MINOR_VERSION}.0-rc.0
      git push --tags triager
    displayName: Git Tag the release candidate