jobs:
- job: create release
  pool:
    vmImage: 'macOS 10.14'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  - script: |
      git config --global user.name "triager"
      git remote add triager https://${GH_TOKEN}@github.com/appium/appium.git > /dev/null 2>&1
      git remote show triager
    displayName: Set TRIAGER as Git user
  - script: npm install
    displayName: Install the Node dependencies
  - script: npm shrinkwrap
    displayName: Create the shrinkwrap
  - script: |
      git tag v${VERSION}
      git push --tags triager
    displayName: Git Tag the release
  - script: |
      npm publish --tag ${NPM_TAG}
    displayName: Publish it