# parameters: # No params yet, but may add later
jobs:
  - job: update_appium_io
    pool:
      vmImage: 'macOS 10.14'
    variables:
      CC: gcc
      CXX: g++
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
    - script: |
        brew install hub
        pip install mkdocs==0.16.3
        git clone https://triager:$GITHUB_TOKEN@github.com/appium/appium.io.git --branch=gh-pages
        pushd appium.io
        git checkout -b docs-$BUILD_SOURCEBRANCH
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)
      displayName: Clone Appium IO Repo
    - script: |
        pushd appium.io
        bundle install
        npm install
        npm run build:docs
        git commit -a -n -m 'Updated docs for latest Appium version'
        git push origin docs-$TRAVIS_TAG
        hub pull-request -b "appium:gh-pages" -h "appium:docs-$TRAVIS_TAG" -m "Update documentation for latest version" | exit 0 # The PR command works but always returns non-negative
      displayName: Make PR with Updated Docs